version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dictionary-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dictionary
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: dictionary-elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dictionary-backend
    environment:
      DATABASE_HOST: postgres:5432
      DATABASE_NAME: dictionary
      DATABASE_USER: admin
      DATABASE_PASSWORD: password
      ELASTICSEARCH_HOST: elasticsearch:9200
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - elasticsearch

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dictionary-frontend
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres:
  elasticsearch:
