### Index Data into Dictionary Index
POST http://localhost:9200/dictionary/_doc
Content-Type: application/json

{
  "id": "1",
  "word": {
    "ru": "собака",
    "en": "dog",
    "tat": "эт"
  },
  "transcription": {
    "ru": "собака",
    "en": "dɔɡ",
    "tat": "эт"
  },
  "description": {
    "ru": "Домашнее животное, известное своей преданностью.",
    "en": "A domestic animal known for its loyalty.",
    "tat": "Өй хайваны, үзенең сабырлыгы һәм дуслыгы белән танылган."
  },
  "created_at": "2023-10-01T12:34:56Z",
  "updated_at": "2023-10-01T12:34:56Z"
}