### Search for a word in a specific language
POST http://localhost:9200/dictionary/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "word.en": "dog"
          }
        }
      ]
    }
  }
}